name: CI

on:
  push:
    branches: 
      - main
      - feature/*
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path:  ~/.gradle/caches
          key:  gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: "Detekt"
        uses: natiginfo/action-detekt-all@1.10.0
        with:
          args: --fail-fast --config detekt-config.yml
  
  unit-test: 
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path:  ~/.gradle/caches
          key:  gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      
      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  instrumented-test:
    name: Instrumented tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path:  ~/.gradle/caches
          key:  gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest

      - name: Copy Test Results
        if: always()
        run: |
          mkdir -p instrumented
          find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec sh -c 'x="{}"; mv "$x" "${x// /}"' \;
          find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} instrumented/ \;
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: instrumented-results
          path: instrumented
 
  report:
    name: Report test results
    runs-on: ubuntu-latest
    needs: [instrumented-test]
    if: ${{ always() }}
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: instrumented-results
 
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
