name: detekt

on:
  push:
    branches: 
      - main
      - feature/*
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest
    
    steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.10.0
         with:
           args: --fail-fast --config detekt-config.yml
